version: '3'
services:
  static-hunt:
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
